### ISSUE TITLE
Feedback de análise dos dados brutos recebidos

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/LIXO-digital-preservartion-BR#3]
Para registro, como tinha dito que postaria um feedback sobre os dados e como foram analisados, para dar embasamento a criação de manual ou procedimento.

## Belo Horizonte
Conferência visual no QGIS.

### O que foi recebido

- bh_pts.geojson.zip
- ENDERECO.csv.zip

O bh_pts.geojson.zip contém só pontos geojosn sem dados.

O ENDERECO.csv.zip é uma planilha CSV de endereços com coordenas.

Ambos foram abertos no QGIS (no mínimo versão 3.10).

### Testes e resultado

Preliminarmente abre-se os arquivos para ver sua integridade e, no caso do arquivo CSV, se há alguma informação útil no _header_ (e.g. identificação das colunas, projeção, se há latitude e longitude etc).

**No QGIS:**
1. Cria-se um novo projeto.
2. Projeção EPSG 31983 (Sirgas 2000/ UTM zona 23S).
3. Adiciona-se uma camada de tiles de imagem aérea na mesma projeção (há várias disponíveis no QGIS).
4. Carregamento do CSV: Menu Camada -> Adicionar Camada -> Adicionar Camada de Texto Delimitado...
5. No diálogo "Texto Delimitado":
![image](https://user-images.githubusercontent.com/4673289/78306992-298e9b80-751b-11ea-88b1-f55e54b97a6c.png)
6. Para visualizar os endereços no QGIS, adicionou-se rótulos para renderizar o número e o nome da rua.
7. Resultado:
![image](https://user-images.githubusercontent.com/4673289/78307792-22688d00-751d-11ea-8e35-47f2a59d0f21.png)

**No JOSM:**
Fiz um teste no JOSM abrindo ENDERECO.csv. Demorou mais de 1 hora para abrir. Portanto, num eventual upload para o OSM, terá que se dividir os dados em partes.

**Comment by IgorEliezer** [comment]
## São Vicente

Verificação e conferência.

### O que foi recebido

- MAPA DE LOTEAMENTOS.dwg

O arquivo dwg é o mapa da área urbana do município. Pode ser aberto em qualquer software CAD (recomendo AutoCAD 2007 ou BricsCAD 17, no mínimo). O mapa está geoposicionado em coordenadas UTM (sem explicitar qual projeção específica), porém os endereços são meros textos no mapa sem atributos em três camadas: emplacamento antigo, oficial e não-oficial.

### Testes e resultado

Para obtenção de dados geoposicionados, foi necessário desenvolver um aplicativo LISP que executado no CAD.

Foram geradas duas planinhas CSV: uma com os números oficiais e outra com números não-oficiais.

Antes do QGIS, preliminarmente abre-se o arquivo CSV para ver a integridade e se foi salvo em codificação UTF-8 (sem BOM) formato Unix LF.

**No QGIS:** 

Foram seguidos os mesmos passos de Belo Horizonte.

Visto que não havia projeção explícita no mapa, foram testadas no QGIS a projeção SAD69 e Sirgas 2000. A SAD69 foi a que se enquadrou.

Resultado abaixo, os números em vermelho são os não-oficiais:

![image](https://user-images.githubusercontent.com/4673289/78311135-60b67a00-7526-11ea-9806-d7bd6e668488.png)

![image](https://user-images.githubusercontent.com/4673289/78311154-68761e80-7526-11ea-9fe7-9497a26bcdf7.png)

**Comment by ppKrauss** [comment]
Olá @IgorEliezer, 

Otimos relatos!

Ainda não temos um padrão de relatório, mas podemos imaginar alguns dados mais. Exemplos:

* Volumetria: estimativas de endereços (geral ou por tipo).

* Detalhe visual e de rótulo original da numeração predial: muito edificios com supostamente um só endereços estão aparentemente apresentando mais de um ponto. Será que existe sobreposição de endereços horizontais (por exemplo sobrelojas)?

* Mais detalhes sobre origem e transformações (a "[linhagem e proveniência dos dados](https://en.wikipedia.org/wiki/Data_lineage#Data_provenance)"). Por  exemplo em BH, os arquivos `bh_pts.geojson.zip` e `ENDERECO.csv.zip` são os originais da prefeitura?

**Comment by IgorEliezer** [comment]
Esta issue está ainda aberta. Fecha?

**Comment by IgorEliezer** [comment]
Fechando por inatividade/efeito esgotado.
