### ISSUE TITLE
Procedimentos para seleção e preservação de material

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/LIXO-digital-preservartion-BR#4]
**Principais questões:**
1. Vamos armazenar tudo o que recebemos na íntegra ou só o que é relevante?
2. Vamos atestar a veracidade de todo o material ou só do material utilizado para gerar o produto-final?

Para essa _issue_, considera-se:
* **Material**: elemento ou carga contendo informação, qualquer seja o formato. Nome mais técnico para arquivos ou documentos.
* **Fornecedor**: entidade que nos cede o material. A maioria é prefeituras e autarquias ligadas.
* **Recepção**: a entrada primária dos materiais;
* **Seleção**: processo de separação e escolha de material sob um critério.
* **Tratamento**: processo de conversão e/ou adaptação do material com o fim de obter dados processáveis, respeitando [autenticidade](http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2011/Lei/L12527.htm#art4).
* **Preservação**: armazenamento do material.
* **Produto-final**: banco de endereço local "liberável" ao público.

(para demais termos, [recomendo o artigo 4º da LAI](http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2011/Lei/L12527.htm#art4))

### Recepção

Até agora o meio predominante para a recepção de material é a caixa de e-mail.

O material chega de forma bem variada, geralmente em três situações:
* Situação 1: um arquivo zip anexado contento todo o material;
* Situação 2: Vários arquivos anexados (tivemos um e-mail contendo mais de 20 anexos);
* Situação 3: um ou mais links apontando para uma página onde há material disponível.

O material é composto por conteúdo relevante e irrelevante para o nosso projeto.

### Seleção

Aqui escolho o **critério da relevância**, isto é, aquilo que não é só essencial para a criação do banco de endereços, mas também material que possa servir como material auxiliar ou ser útil para o OpenStreetMap.

O critério de relevância é mais amplo do que o que é simplesmente essencial. Por exemplo, essencialmente nós precisamos só dos lotes e eixos das vias; os contornos de quadras não são essenciais mas podem servir de para distinguir qual face do lote está voltado para a rua.

Material que é servível para o OpenStreetMap e que não foge do nosso escopo pode ser considerado relevante. Exemplos: divisas de bairros e contornos de equipamentos públicos.

Material irrelevante será descartado.

### Tratamento

Muitas vezes o material vem em formato que não é compatível com nossos processos, mas contém informações úteis. Este material então será submetido à conversão e adaptação, preservando as informações.

Em outras palavras: geramos um material intermediário, mas não geramos ou alteramos informações, só as tornamos "inteligíveis" para os nossos processos.

### Preservação e autentificação SHA256 de material com perda da integridade/primariedade

Nos casos da "Situação 1" acima, na seleção teremos que deszipar o material recebido, descartar o material irrelevante, e o material relevante será processado e preservado.

Só o fato de deszipar e descartar o material irrelevante provoca a perda da integridade, pois não é mais exatamente o material como veio do fornecedor. Destaco que o material remanescente, i.e. relevante, é ainda autêntico, pois as informações são como vieram do fornecedor.

Então o que de fato estará sendo autenticado com chave SHA256: o material que o fornecedor nos envia ou o material relevante selecionado por nós?

A situação é mais drástica nos casos em que o material teve que ser convertido (hipoteticamente CAD ou PDF para CSV). O material intermediário é nosso, mesmo que as informações sejam autênticas.

Este assunto/issue precisa ainda ser melhor desenvolvido.

**Comment by ppKrauss** [comment]
Olá @IgorEliezer , otima proposta! Vamos aguardar os demais darem um sinal de vida... Por hora apenas alguns adendos de minha parte:

* do ponto de vista jurídico a doação de um patrimônio e a "contrato" de licença sobre uso e usufruto desse patrimônio, são relativos ao que o doador definiu, não o que nós (receptores) definimos. **Não podemos adulterar o material fornecido**. Ainda assim, tecnicamente, para o bom entendedor as operações de *rename*, *zip* e/ou *unzip* não adulteram arquivos digitais. Como receptores e **curadores** das obras doadas, temos o direito de desmembrar arquivos zip ou anexos de email em seus arquivos componentes.  <br/>O que importa, para garantir a integridade e rastreabilidade da obra doada, é o *digest* da função [hash criptográfica](https://en.wikipedia.org/wiki/Cryptographic_hash_function) (ex. SHA256)  de cada arquivo (ou se decidirmos reunir similares num só zipadão).

* já estamos montando o documento rascunho da [Spec02-workflow](https://github.com/AddressForAll/specifications/blob/master/docs/spec02-workflow.md), a norma técnica do Instituto AddressForAll que regerá (a partir da versão 1) o nosso *workflow* e as atribuições básicas de cada equipe.

* podemos simplificar algumas coisas, o detalhamento da burocracia é importante todavia, até mesmo para ser documentado, pois servirá de subsídio na hora da automação, quando aumentar o volume de material e o número de prefeituras fornecendo dados. A burocracia, uma vez aprovada e testada conosco mais artesanalmente, terá a sua documentação efetivamente usada como [requisito de software](https://en.wikipedia.org/wiki/Requirements_analysis).

-----

O desenho geral do *workflow* já podemos tomar como definitivo:

![](https://github.com/AddressForAll/specifications/raw/master/docs/assets-spec02/image5.png)

Até a publicação no UrbiGIS para efeitos de consulta pública, pelo que entendi, está tranquilo e todos em consenso.
Uma vez pubicado no UrbiGIS o que a Equipe de Relacionamento faria é:

1. Solicita por email a licença/aceite do doador, <br/>PS: já citando no email  o número de bytes do arquivo doado, o seu *hash* (como referêcia jurídica do objeto doado) e o link para o UrbiGIS (como atestado visual do conteúdo doado).

2. Uma vez concedida a licença, já pode fazer as duas coisas indicadas no fluxo:

   2.1. registro para a preservação digital de 20 anos; e 
   2.2. postagem no nosso *PostGIS server online*,  para encaminhar à equipe de processamento e iniciar ingestão.

**Comment by IgorEliezer** [comment]
Resumidamente, já na direção de decidir um padrão de armazenamento, ao menos por hora:

0) O módulo básico do projeto são os municípios. Então tudo é organizado por municípios.

1) Cada município terá uma pasta `BR-EE-NomeMunicipio`, onde `EE` é a sigla do Estado e `NomeMunicipio` é nome do município sem espaços, acentos e preposições.

2) Cada pasta de município teria as seguintes pastas:
* **input** - preservação de material fornecido relevante.
* **output** - material final.
* **license** - pasta da licença.
* **temp** - material preservado temporamente, ex.: material gerado em etapa intermediária entre input e output devido a tratamento. Será descartado uma vez que o output se estabelece pela licença e ausência de contestação.

3) O processo, usando como exemplo um material que possui conteúdo irrelevante e que precise de tratamento: um zip contendo um arquivo CAD, vários PDFs e PNGs. 

* Obtém o material.
* Análise e seleção.
  * O zip é descompactado.
  * Material irrelevante é descartado (PDF e PNG).
  * Material relevante (CAD) será recompactado, autenticado com _hash_ e salvo em **input** como prova do que foi recebido.
(**_questão:_** o valor do _hash_ será armazenado como e onde?)
* Tratamento (converte-se o CAD em Shapefile), obtém-se então o que poderíamos chamar de "material processável"
  * Obs: Considera-se "material processável" o material que é inteligível pelas plataformas GIS (QGIS, UrbiGIS etc).
* Consulta pública: sugiro o mesmo tempo da Lei de Acesso à Informação, 20 dias, prorrogável por mais 10 no caso de haver contato antes de expirar o 1º período.
* Cópia 1 vai para Processamento: 
  * Ingestão --> Análise e Filtragem --> Incorporação --> Publicação
* Cópia 2 vai para Preservação:
  * Vão para a preservação: os arquivos + metadados (SHA256 etc)

**Comment by IgorEliezer** [comment]
Atualizei o item 3 de https://github.com/AddressForAll/digital-preservartion-BR/issues/4#issuecomment-663873600

**Comment by IgorEliezer** [comment]
Esta issue está ainda aberta. Fecha?

**Comment by IgorEliezer** [comment]
Fechando por inatividade/efeito esgotado.
